### ISSUE TITLE
Move accessToken to request class

### ISSUE THREAD

**Issue by ioncreature** [cre-o/ok.ru#2]
Why do you store access token globally?
I have a lot of users and every user have their own access_token. It seems strange that we need to set user access_token globally before make requests. Is there a way to move access_token inside OkApi class?

**Comment by cre-o** [comment]
Hi ioncreature!
You can just do the following thing:
```coffeescript
ok  = require('ok.ru')
# later in code...
array = 
  firstUser: { token: 'abc' }
  secondUser: { token: 'cba' }

async.each array, (item, each_callback) ->
  # Each time you are making a call, each time you overwriting previous token
  ok.setAccessToken(item.token)
  # so next >> ok.post << call will be constructed with new token
  # will produce
  ok.post token: 'abc'
  ok.post token: 'cba'
```

Have a nice day!
