### ISSUE TITLE
Function parametrize produces incorrect urls

### ISSUE THREAD

**Issue by ioncreature** [cre-o/ok.ru#3]
``` js
ok.get({
    method: 'photos.getPhotos',
    param1: undefined,
    param2: undefined
}, callback );
```

Produces urls like
`method=photos.getPhotos&param1=undefined&param2=undefined`

instead of 
`method=photos.getPhotos&param1=&param2=`

**Comment by cre-o** [comment]
Closing this issue because anybody is confirmed need of this feature.
